### ISSUE TITLE
Fazer que o secretario só tenha acesso à sua página e mais ninguém tenha

### ISSUE THREAD

**Issue by xXD4rkSoulXx** [anotherlusitano/ESTG-ES2-Infoget#114]
O que eu queria mesmo era esta na ilha do estudo......

**Comment by Afonso295** [comment]
o profissional

**Comment by anotherlusitano** [comment]
![image](https://github.com/user-attachments/assets/09466b4e-5f39-4f2e-9910-461e92fbe7ba)

**Comment by Afonso295** [comment]
![image](https://github.com/user-attachments/assets/1cb784a7-61f9-40b3-97f2-fe76ba57863b)

**Comment by Afonso295** [comment]
![image](https://github.com/user-attachments/assets/f60a9607-b00f-452c-a7fb-c2f4c81f41d5)
