### ISSUE TITLE
Definir Modelo de Casos de Uso

### ISSUE THREAD

**Issue by anotherlusitano** [anotherlusitano/ESTG-ES2-Infoget#3]

**Comment by joaoaguiiar** [comment]
[ModelosDeCasoDeUso.txt](https://github.com/user-attachments/files/17292327/ModelosDeCasoDeUso.txt)

## Modelos de Casos de Uso

### 1. Registo de Users

**Atores Principais:** Alunos, Professores  
**Objetivo:** Permitir que novos users se registem para usufruir das funções do Infoget.

**Fluxo Principal:**
1. O user acessa a página de registo.
2. O sistema apresenta o formulário de registo (e-mail, senha e confirmação de senha).
3. O user preenche as informações e envia.
4. O sistema valida os dados e cria a conta do usuário.
5. O sistema envia um e-mail de confirmação ao usuário.
6. O user começa a acessar o sistema.

**Fluxo Alternativo:**
- E-mail já registado: O sistema exibe uma mensagem informando que o e-mail já está em uso.
- Erros de validação: O sistema indica erros de preenchimento (senha fraca, e-mail inválido).

---

### 2. Login no Sistema

**Atores Principais:** Alunos, Professores  
**Objetivo:** Permitir que os usuários façam login na plataforma.

**Fluxo Principal:**
1. O user acessa a página de login.
2. O sistema solicita e-mail e senha.
3. O user insere as informações.
4. O sistema verifica as credenciais e concede ou não o acesso.
5. O user é redirecionado à página do Infoget.

**Fluxo Alternativo:**
- Senha incorreta: O sistema exibe uma mensagem de erro e oferece um link para recuperação de senha.

---

### 3. Inscrição em Disciplinas

**Ator Principal:** Alunos  
**Objetivo:** Permitir que o aluno se inscreva nas disciplinas do seu curso.

**Fluxo Principal:**
1. O aluno faz login no sistema.
2. O sistema exibe as opções do menu; o aluno seleciona "Inscrição em Disciplinas".
3. O sistema apresenta a lista de disciplinas disponíveis conforme o curso e semestre.
4. O aluno escolhe as disciplinas desejadas.
5. O aluno confirma a inscrição.
6. O sistema valida os pré-requisitos e a disponibilidade de vagas, confirmando a inscrição.

**Fluxo Alternativo:**
- Vaga não disponível: O sistema exibe uma mensagem de erro e oferece a opção de inscrição em outro turno.
- Pré-requisitos não atendidos.

---

### 4. Consulta de Horários

**Atores Principais:** Alunos, Professores  
**Objetivo:** Permitir que os usuários consultem o horário das aulas.

**Fluxo Principal:**
1. O aluno/docente faz login no Inforestudante.
2. O aluno seleciona "Calendário"; o docente seleciona "Horário de Aulas".
3. (Somente para o aluno) O sistema exibe o calendário universitário em que o aluno está inscrito.
4. (Somente para o professor) O sistema exibe o horário das disciplinas que leciona e as salas de aula.
5. O aluno/docente consulta o horário e as salas.

**Fluxo Alternativo:**
- Alterações de horário: Se houver uma mudança, o sistema exibe uma notificação indicando as alterações.

---

### 5. Pagamento de Propinas

**Ator Principal:** Alunos  
**Objetivo:** Permitir que o aluno realize o pagamento das propinas através da plataforma.

**Fluxo Principal:**
1. O aluno faz login no sistema.
2. O aluno acessa a seção "Propinas" ou "Pagamentos".
3. O sistema exibe as parcelas a serem pagas.
4. O aluno seleciona a parcela desejada.
5. O sistema gera os dados para pagamento.
6. O aluno realiza o pagamento e confirma no sistema.
7. O sistema atualiza o estado e exibe a confirmação.

**Fluxo Alternativo:**
- Erro no pagamento: Se houver erro, o sistema informa e solicita que o aluno tente novamente.

---

### 6. Consulta e Atribuição de Notas

**Atores Principais:** Alunos, Professores  
**Objetivo:** Permitir que o aluno visualize as suas notas e que o docente as atribua.

**Fluxo Principal (Aluno):**
1. O aluno faz login no sistema.
2. No menu, seleciona "Consulta de Notas".
3. O sistema apresenta a lista de disciplinas.
4. O aluno seleciona a disciplina desejada.
5. O sistema exibe as notas obtidas.

**Fluxo Principal (Professor):**
1. O professor faz login no sistema.
2. No menu, seleciona "Atribuição de Notas".
3. O sistema apresenta as disciplinas lecionadas.
4. O professor atribui as notas.

**Fluxo Alternativo (Aluno):**
- Notas pendentes: O sistema informa que as notas ainda não foram atribuídas.

---

### 7. Solicitação de Documentos Acadêmicos

**Ator Principal:** Alunos  
**Objetivo:** Permitir que o aluno solicite documentos acadêmicos.

**Fluxo Principal:**
1. O aluno faz login no sistema.
2. O aluno acessa o menu "Documentos Acadêmicos".
3. O sistema exibe as opções de documentos disponíveis.
4. O aluno seleciona o documento desejado.
5. O sistema processa o pedido e disponibiliza o download.

**Fluxo Alternativo:**
- Documento não disponível: O sistema informa que o aluno deve consultar pessoalmente na secretaria.

---

### 8. Acesso e Atualização de Dados Pessoais

**Ator Principal:** Alunos  
**Objetivo:** Permitir que o aluno acesse e atualize seus dados pessoais.

**Fluxo Principal:**
1. O aluno faz login no sistema.
2. O aluno acessa o menu "Meus Dados".
3. O sistema exibe os dados atuais.
4. O aluno altera os dados e confirma.
5. O sistema valida e guarda as mudanças.

**Fluxo Alternativo:**
- Erro na validação: O sistema exibe uma mensagem solicitando a correção de dados incorretos.

---

### 9. Envio de Materiais Didáticos

**Ator Principal:** Professores  
**Objetivo:** Permitir que os docentes façam upload de materiais de apoio.

**Fluxo Principal:**
1. O professor faz login no sistema.
2. O professor acessa o menu "Materiais de Apoio".
3. O sistema exibe as disciplinas lecionadas.
4. O professor seleciona a disciplina.
5. O sistema apresenta a opção de "Carregar Documentos".
6. O professor escolhe os arquivos e os insere no sistema.
7. O sistema faz o upload e disponibiliza os materiais para os alunos.

**Fluxo Alternativo:**
- Formato ou arquivo inválido: O sistema solicita a correção.
- Limite de tamanho de arquivo: O sistema informa a necessidade de compressão do arquivo.

**Comment by anotherlusitano** [comment]
@joaoaguiiar o modelo de caso de uso devia ser um ficheiro dentro da pasta `docs`.

E o modelo de caso de uso devia ser uma imagem com as interações do utilizador, aqui está um exemplo de como deveria ser:
![image](https://github.com/user-attachments/assets/a4f7a5c6-8a05-4231-b46f-97fc728c2eed)

**Comment by joaoaguiiar** [comment]
Olá, @anotherlusitano , peço desculpa pelo equívoco causado, pensei que fosse o suficiente fazer somente em documento texto.
Fica aqui o Diagrama de Caso de Uso que me pediste da forma ''correta''. 
Se houver alguma mudança necessária a fazer, diz-me que eu altero o mais rápido possivel sem problema. 
![DiagramaInfoget](https://github.com/user-attachments/assets/c9a8829e-5715-42a1-9b93-21ec7f2d7ecf)

**Comment by anotherlusitano** [comment]
Olá @joaoaguiiar, está quase perfeito mas algumas coisas devem ser mudadas.

Nomeadamente a falta de um bonequinho chamado "Secretario" e alguns balões que estão a mais.
Só precisas ir ao ficheiro de [UserStories](https://github.com/anotherlusitano/ESTG-ES2-Infoget/blob/main/docs/UserStories.md) que vai estar lá tudo o que precisamos ter no diagrama.

De resto é tudo, e desculpa por não ter dito logo quais as coisas necessárias no diagrama

**Comment by anotherlusitano** [comment]
Está perfeito :)
Agora podes meter essa imagem dentro da pasta `docs` e fechar esta tarefa

**Comment by anotherlusitano** [comment]
Está quase tudo feito, só é preciso tirar as setas de registar professor e de registar aluno aluno, nos bonecos `professor` e `aluno`.
E se possivel, separar um pouco as setas e os bonecos para ficar mais organizado de se ver.

Depois é só meter a imagem na pasta `docs` e ta tudo :)

**Comment by joaoaguiiar** [comment]
Peço desculpa por hoje não ter ido, infelizmente foi devido a casos familiares eu com todo o gosto tinha ido à aula de hoje.. 
Com isto dito, está finalmente feito e vou já a seguir de enviar isto meter a imagem final na pasta docs. 
Vou aproveitar agora que finalmente estou em casa também para ir despachando um ou outro ponto.
