### ISSUE TITLE
Alterar o título das páginas de Laravel para Infoget

### ISSUE THREAD

**Issue by xXD4rkSoulXx** [anotherlusitano/ESTG-ES2-Infoget#51]

**Comment by xXD4rkSoulXx** [comment]
@joaoaguiiar , não sei se vais conseguir ver esta mensagem, porque nenhum pull foi criado para poder comentar. Não podes continuar a meter tarefas feitas sem estar feitas. Os testes estão com erro. Não tem como mostrar ao stor aquilo a dar erro. Testa e verifica se funciona antes de enviar, é o mínimo. Por esse motivo volto a meter no To Do.

**Comment by joaoaguiiar** [comment]
Os erros não são somente na importação de bibliotecas? Muitos dos testes estavam há dias na aba de In Review mesmo por isso e ninguém me ajudou :(

**Comment by xXD4rkSoulXx** [comment]
Não sei se foi de importação de bibliotecas, mas convém mencionares isso também a nós já que não iriamos adivinhar isso. Tive muito ocupado estes dias a fazer as tarefas mais importantes do projeto sem receber nenhum tipo de ajuda, então não tive tempo de verificar porque os testes davam erro e o porquê por haver prioridades. Tem como mandares printscreen dos teus testes a funcionar e me ajudares a fazer no meu funcionar?
![image](https://github.com/user-attachments/assets/acccd2ee-aa0d-4e95-859c-c492d08e232e)

**Comment by joaoaguiiar** [comment]
Eu tenho a certeza de que os erros são somente na importação de bibliotecas e/ou em caminhos/nomes de classes. 
Como clonei o projeto nada disso causará interferência portanto o que posso deduzir é que: 

1. Para os arquivos PHP pode faltar o seguinte: 
`use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;` 
ou o composer não instalado. (composer install) 

2.  Para os arquivos JSX só consigo calcular que pode faltar bibliotecas(mas que duvido imenso infelizmente) como jest ou testing-library/react
`npm install --save-dev jest @testing-library/react @testing-library/jest-dom`

Como já disse também pode ser de erros de importação do meu código em si como por exemplo:
`import { render, screen } from '@testing-library/react';
import Chatbot from './Chatbot';`

E como não sei se usaram fetch ou mocks anteriormente também se calhar é preciso meter isto: npm install --save-dev whatwg-fetch


Tirando isto não consigo pensar em mais nada. Se não conseguir até às 10 da manhã de amanhã eu acarreto com as consequências claro.

**Comment by xXD4rkSoulXx** [comment]
Tenho composer instalado porque se não o meu Laravel não abriria.
Eu dei esse npm install --save-dev jest @testing-library/react @testing-library/jest-dom  para poder testar se não nunca teria como te mandar aquele print
Testei agora o npm install --save-dev whatwg-fetch e o erro persiste.
Só resta ser os tais erros do teu código que mencionaste, mas se for isso deveria ser algo que deverias ter emendado.
Mas tens algum printscreen dos testes a funcionar como tinha pedido?

**Comment by joaoaguiiar** [comment]
Boas Diogo, não tenho permissão para editar as branches portanto deixo aqui ( mas se quiseres mete permissão que alterarei com todo o gosto 👍 )
O #141 fica resolvido se alterarmos o caminho para `Controller: app/Http/Controllers/CursoDisciplinaController.php` 
`Route: routes/web.php`
O #137 fica resolvido se alterarmos o caminho para `resources/js/Pages/Professor/Turmas.jsx.`
O #132 fica resolvido se alterarmos o caminho para `resources/js/Pages/Profile/AlunoProfile.jsx` (esta é a única que não tenho a certeza)
O #92 fica resolvido se alterarmos o caminho para `resources/js/Pages/Auth/Login.jsx.`
O #94 fica resolvido se alterarmos o caminho para `resources/js/Pages/Chatbot.jsx.`
O #133 fica resolvido se alterarmos o caminho para  `resources/js/Pages/Profile/ProfessorProfile.jsx.`
O #139 fica resolvido se alterarmos o caminho para `app/Http/Controllers/ProfessorController.php.`
O #134 fica resolvido se alterarmos o caminho para `resources/js/Pages/Aluno/Curriculo.jsx.`
O #142 fica resolvido se alterarmos o caminho para `app/Http/Controllers/SecretariaController.php.`
O #135 fica resolvido se alterarmos o caminho para `app/Http/Controllers/ProfessorDisciplinaController.php.`
O #140 fica resolvido se alterarmos o caminho para `app/Http/Controllers/CursosController.php.`
O #138 fica resolvido se alterarmos o caminho para `app/Http/Controllers/AlunoController.php.`
O #93 fica resolvido se alterarmos o caminho para `resources/js/Pages/Auth/RecuperarSenha.jsx.`
O #136 fica resolvido se alterarmos o caminho para `app/Http/Controllers/ProfessorDisciplinaController.php.`

**Comment by anotherlusitano** [comment]
> Boas Diogo, não tenho permissão para editar as branches portanto deixo aqui ( mas se quiseres mete permissão que alterarei com todo o gosto 👍 ) O #141 fica resolvido se alterarmos o caminho para `Controller: app/Http/Controllers/CursoDisciplinaController.php` `Route: routes/web.php` O #137 fica resolvido se alterarmos o caminho para `resources/js/Pages/Professor/Turmas.jsx.` O #132 fica resolvido se alterarmos o caminho para `resources/js/Pages/Profile/AlunoProfile.jsx` (esta é a única que não tenho a certeza) O #92 fica resolvido se alterarmos o caminho para `resources/js/Pages/Auth/Login.jsx.` O #94 fica resolvido se alterarmos o caminho para `resources/js/Pages/Chatbot.jsx.` O #133 fica resolvido se alterarmos o caminho para `resources/js/Pages/Profile/ProfessorProfile.jsx.` O #139 fica resolvido se alterarmos o caminho para `app/Http/Controllers/ProfessorController.php.` O #134 fica resolvido se alterarmos o caminho para `resources/js/Pages/Aluno/Curriculo.jsx.` O #142 fica resolvido se alterarmos o caminho para `app/Http/Controllers/SecretariaController.php.` O #135 fica resolvido se alterarmos o caminho para `app/Http/Controllers/ProfessorDisciplinaController.php.` O #140 fica resolvido se alterarmos o caminho para `app/Http/Controllers/CursosController.php.` O #138 fica resolvido se alterarmos o caminho para `app/Http/Controllers/AlunoController.php.` O #93 fica resolvido se alterarmos o caminho para `resources/js/Pages/Auth/RecuperarSenha.jsx.` O #136 fica resolvido se alterarmos o caminho para `app/Http/Controllers/ProfessorDisciplinaController.php.`

Eu tenho certeza que tens permissão, já que és colaborador do projecto.

**Comment by joaoaguiiar** [comment]
Eu tenho a certeza que não faria um texto enorme invés de editar logo se pudesse :) 

![Screenshot_1](https://github.com/user-attachments/assets/9e9e6a45-99bb-46f8-8169-bfeb82012825)

**Comment by xXD4rkSoulXx** [comment]
> Boas Diogo, não tenho permissão para editar as branches portanto deixo aqui ( mas se quiseres mete permissão que alterarei com todo o gosto 👍 ) O #141 fica resolvido se alterarmos o caminho para `Controller: app/Http/Controllers/CursoDisciplinaController.php` `Route: routes/web.php` O #137 fica resolvido se alterarmos o caminho para `resources/js/Pages/Professor/Turmas.jsx.` O #132 fica resolvido se alterarmos o caminho para `resources/js/Pages/Profile/AlunoProfile.jsx` (esta é a única que não tenho a certeza) O #92 fica resolvido se alterarmos o caminho para `resources/js/Pages/Auth/Login.jsx.` O #94 fica resolvido se alterarmos o caminho para `resources/js/Pages/Chatbot.jsx.` O #133 fica resolvido se alterarmos o caminho para `resources/js/Pages/Profile/ProfessorProfile.jsx.` O #139 fica resolvido se alterarmos o caminho para `app/Http/Controllers/ProfessorController.php.` O #134 fica resolvido se alterarmos o caminho para `resources/js/Pages/Aluno/Curriculo.jsx.` O #142 fica resolvido se alterarmos o caminho para `app/Http/Controllers/SecretariaController.php.` O #135 fica resolvido se alterarmos o caminho para `app/Http/Controllers/ProfessorDisciplinaController.php.` O #140 fica resolvido se alterarmos o caminho para `app/Http/Controllers/CursosController.php.` O #138 fica resolvido se alterarmos o caminho para `app/Http/Controllers/AlunoController.php.` O #93 fica resolvido se alterarmos o caminho para `resources/js/Pages/Auth/RecuperarSenha.jsx.` O #136 fica resolvido se alterarmos o caminho para `app/Http/Controllers/ProfessorDisciplinaController.php.`

Que estranho, eu movi para essa pasta agora para testar e continua a não funcionar. Consegues mandar printscreen a funcionar?

**Comment by xXD4rkSoulXx** [comment]
> Eu tenho a certeza que não faria um texto enorme invés de editar logo se pudesse :)
> 
> ![Screenshot_1](https://private-user-images.githubusercontent.com/166999868/394045556-9e9e6a45-99bb-46f8-8169-bfeb82012825.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3ODc5MTcsIm5iZiI6MTczMzc4NzYxNywicGF0aCI6Ii8xNjY5OTk4NjgvMzk0MDQ1NTU2LTllOWU2YTQ1LTk5YmItNDZmOC04MTY5LWJmZWI4MjAxMjgyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQyMzQwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NGQxY2JjY2Y2OThkYTJiYmYxODgwMThlNjM0NDE2NWMwZjU0NmYzNjgyOTAxM2FkNzM2ZDZhNjEwZGRlMDIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LizU__8MEnah-wWQWaydeaKDJRSdoL1XV6dRGtPvJqg)

Tenta de novo, já tivemos a ver as permissões e acho que deves conseguir agora

**Comment by joaoaguiiar** [comment]
Continuo a não conseguir editar mas pouca diferença faz, não está a funcionar. Já fui verificar e não pode ser do store no Controller porque está compatível. Também não pode ser a route para o CursoDisciplinaController(no exemplo que estou a tentar) pois está correta também. E com o caminho agora correto também. Não sei genuinamente o que pode estar a falhar.

**Comment by anotherlusitano** [comment]
> Eu tenho a certeza que não faria um texto enorme invés de editar logo se pudesse :)
> 
> ![Screenshot_1](https://private-user-images.githubusercontent.com/166999868/394045556-9e9e6a45-99bb-46f8-8169-bfeb82012825.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3ODg4NjksIm5iZiI6MTczMzc4ODU2OSwicGF0aCI6Ii8xNjY5OTk4NjgvMzk0MDQ1NTU2LTllOWU2YTQ1LTk5YmItNDZmOC04MTY5LWJmZWI4MjAxMjgyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQyMzU2MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZmEyYTU1YjE4OThiZTNjNjQxNmY2NTZkYjdhYzFhNDliMTUyNWE5ODNlYzY4YjhlNTYxMzYzYWY2MzY0NjY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gwDGxD1pZ8p75XDww_xKR3Vsdz9MJxhuzcISEZWlPXA)

Isto é da onde? Porque tenho a certeza que se fores a algum ficheiro vai aparecer o simbolo de editar.
E qualquer coisa é só usares o Github Desktop para dares pull das alterações e editares a branch.
